export interface LoginResponse {
  access: string;
  refresh: string;
  pin: string;
}

export interface User {
  id: number;
  inn: string;
  pin: string ;
  token: string;
  first_name: string ;
  last_name: string ;
  email: string;
  surname: string ;
  alert_number: number;
  auditor_fund: boolean;
  calendar: boolean;
  capacity: boolean;
  chat: boolean;
  conversion: boolean;
  data_of_birth: string;
  discipline: boolean;
  division: string;
  efficiency: number;
  flow: boolean;
  gender: string;
  id_institute: number;
  imeag: string;
  is_admin_create_discipline: boolean;
  is_admin_entrant: boolean;
  is_admin_human_department: boolean;
  is_admin_it_department: boolean;
  is_admin_kpi: boolean;
  is_admin_of: boolean;
  is_admin_of_news: boolean;
  is_admin_reference: boolean;
  is_employee: boolean;
  is_head_of: boolean;
  is_mol_of: boolean;
  is_online: boolean;
  is_order_regist_of: boolean;
  is_singer_kpi: boolean;
  is_stud: boolean;
  is_student: boolean;
  is_super_singer_kpi: boolean;
  is_superuser: boolean;
  is_support_of: boolean;
  is_univer_admin: boolean;
  is_zakupki_admin: boolean;
  is_zakupki_head: boolean;
  journal_order: boolean;
  kpi: boolean;
  number_phone: string;
  order: boolean;
  position: string;
  registration: boolean;
  report: boolean;
  rup: boolean;
  statistic: boolean;
  stavka: number;
  struct: boolean;
  support: boolean;
  task: boolean;
  unique_code_user: string;
  univer_branch: string ;
  univer_branch_name: string ;
  user: number;
  user_type: string;
}